[[redirects]]
  from = "/api/kick/*"
  to = "https://api.kick.com/public/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/kick-v2/*"
  to = "https://api.kick.com/public/v2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/whitebit/*"
  to = "https://whitebit.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
